POST http://localhost:8080/v1/api/archive
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNjg1MzgyNTA3LCJleHAiOjE2ODUzODQzMDd9.cM0bhu9bKCJudX1IVF65qvJIbeDCa7wolWQucNMWpxQ

{ "title" : "The Dogs", "body": "Lorem Ipsum, The Dogs Quick Brown", "author" : "B Json" }
