POST http://localhost:8080/v1/api/archive
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNjg1NTU0NzY2LCJleHAiOjE2ODU1NTY1NjZ9.UfUg7NNLObCiClXeCxHsZcBwrgZ1Xdxth4a-isjzdZg

{ "title" : "Hello World Dogs", "body": "Lorem Ipsum, The Dogs Quick Brown", "author" : "B Json" }
