GET http://localhost:8080/v1/api/archive?pageIndex=0&pageSize=10&sortBy=title&sortDirection=DESC
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNjg1NDE1OTUyLCJleHAiOjE2ODU0MTc3NTJ9._bPGQLO6Reqbmj_0n5l48o2yIUdI-0XCYAqW7KoJhVI
