GET http://localhost:8080/v1/api/archive?pageIndex=0&pageSize=10&sortBy=title&sortDirection=DESC
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNjg1NTU2OTIyLCJleHAiOjE2ODU1NTg3MjJ9.QQtf7W0uoRPqrorp3sjCZZsa6oqiiR2P6NVpMLuqo1o
